### PR TITLE
Adds Single Div Project to list

### PR DESCRIPTION
**Pull request by ManrajGrover**
Adds Single Div Project to list

### CODE REVIEW

**Comment by sotayamashita** [comment]
@ManrajGrover I appreciate your work but I have a question of section title.  I don’t know what to say but "Miscellaneous" is popular words ? Everybody can understand easily ?

**Comment by ManrajGrover** [comment]
@sotayamashita Thank you for appreciating. I've followed what [Awesome](https://github.com/sindresorhus/awesome) list does (It also has a "Miscellaneous" section). I'm not sure how to categorise it as well. But it surely doesn't fit categories already mentioned.

**Comment by sotayamashita** [comment]
@ManrajGrover I got it. You do not need to change section title right now. If number of item is increasing, we will rethink the name.

Thanks again

**Comment by ManrajGrover** [comment]
@sotayamashita Works! Thank you for creating this awesome lists!

**Pull request merged**
