### PR TITLE
Add Wing (CSS Framework)

### PR DESCRIPTION
**Pull request by KingPixil**
I was looking at this list, and realized it didn't include a fairly new framework, [Wing](http://usewing.ml).

### CODE REVIEW

**Comment by sotayamashita** [comment]
@KingPixil 

First of all, I am very appreciate your work. :bow: I am not great engineer but I decline your PR now because it's not widely recommended yet. I will add your repo in the future.

**Comment by KingPixil** [comment]
No Problem! Thanks for appreciating :+1:

**Comment by KingPixil** [comment]
Hey, so Wing has gotten more stars, and is recommended by campers from FreeCodeCamp, the communities on HN + Reddit. I think it is ok to add it now?

**Comment by sotayamashita** [comment]
@KingPixil I am sorry but other framework has 1000 start at least.

**Comment by KingPixil** [comment]
I see, no problem @sotayamashita hopefully this happens soon :)

**Comment by sotayamashita** [comment]
@KingPixil I shared your great library on Twitter. Go for it !!!

**Comment by KingPixil** [comment]
@sotayamashita Wing now has 1.2k stars, is it possible to add now? 😛

**Comment by sotayamashita** [comment]
@KingPixil Awesome 🎉

**Pull request merged**
