### PR TITLE
Fix broken link for sanitize.css

### PR DESCRIPTION
**Pull request by keik**

### CODE REVIEW

**Comment by sotayamashita** [comment]
@keik Wow. I appreciate your work but would you mind change this url to `https://github.com/jonathantneal/sanitize.css`. thanks in advance.

**Comment by keik** [comment]
Thanks. No I don't mind.
 But do we like to link to repository's page than project's own page?

 It seems that some other products listed link to project's own page, like [LESS](http://lesscss.org/). And others link to repository's page, like [Myth](https://github.com/segmentio/myth), in spite of [Myth's own page](http://www.myth.io/).

**Comment by sotayamashita** [comment]
@keik I understand its problem so I am about to use repository page instead of project page. What do you think ?

**Comment by keik** [comment]
👍

**Pull request merged**
