### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by script-old**
Added Pure.css framework

### CODE REVIEW

**Comment by sotayamashita** [comment]
Thank you for your effort

**Comment by script-old** [comment]
I'm glad I was able to help!

**Comment by sotayamashita** [comment]
@script-old Thank you so much for your kind cooperation. If you have a time, please check this issue.

**Comment by script-old** [comment]
What kind of issue is it?

**Comment by sotayamashita** [comment]
@script-old I am sorry. I forgot add a link. Here is 
https://github.com/sotayamashita/awesome-css/issues/8

**Pull request merged**
