### PR TITLE
Add css reset and normalize

### PR DESCRIPTION
**Pull request by red2678**

### CODE REVIEW

**Comment by sotayamashita** [comment]
@red2678 Thank you for your corporation but please sort in ascending alphabetical order, i.e. a to z. It is written in [CONTRIBUTING.md](https://github.com/sotayamashita/awesome-css/blob/master/CONTRIBUTING.md)

**Comment by red2678** [comment]
@sotayamashita my bad, there ya go.

**Comment by sotayamashita** [comment]
@red2678 Thank you for your quick fix.

**Comment by red2678** [comment]
:+1:

**Pull request merged**
